version: "3.1"

services:
  cloudflared:
    image: erisamoe/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
  
  rss-bridge:
    image: ghcr.io/erisa/rss-bridge
    restart: unless-stopped
    environment:
      - RSSBRIDGE_TwitterV2Bridge_twitterv2apitoken=${RSSBRIDGE_TwitterV2Bridge_twitterv2apitoken}

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --label-enable --cleanup
    restart: always