# fly.toml app configuration file generated for rss-bridge on 2023-04-20T22:01:10+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rss-bridge"
primary_region = "lhr"
kill_signal = "SIGINT"
kill_timeout = 5

[experimental]
  auto_rollback = true

[[services]]
  protocol = "tcp"
  internal_port = 80
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "30s"
    restart_limit = 0

  [http_service]
    # automatically start machines
    auto_start_machines = true
    # automatically stop machines
    auto_stop_machines = true
