name: Build Image on Commit and Release

on:
  push:
    branches:
      - 'master'

env:
  DOCKERHUB_SLUG: rssbridge/rss-bridge
  GHCR_SLUG: ghcr.io/erisa/rss-bridge

jobs:
  bake:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -  
        name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.GHCR_SLUG }}
          tags: |
            type=raw,value=latest
            type=sha
            type=ref,event=tag,enable=${{ startsWith(github.ref, 'refs/tags/20') }}
            type=raw,value=stable,enable=${{ startsWith(github.ref, 'refs/tags/20') }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/bake-action@v4
        with:
          files: |
            ./docker-bake.hcl
            ${{ steps.docker_meta.outputs.bake-file }}
          targets: image-all
          push: true
